### ISSUE TITLE
Can't call method "parent" on an undefined value at scraper.pl line 113.

### ISSUE THREAD

**Issue by hanecak** [soit-sk/brno_sever_usneseni_rady#1]
Scraper aktualne konci s chybou:

```
Page: http://www.sever.brno.cz/volene-organy-s/646-aktualni-usneseni-rady.html
Year: 2010
Can't call method "parent" on an undefined value at scraper.pl line 113.
```

**Comment by michal-josef-spacek** [comment]
Snažím se to opravit. Vyhodili ze stránek starší roky, což je jednoduché opravit. Bohužel mají chybu ve stránkách, takže jsem jim napsal, ať to zkusí opravit. Počkám jak se vyjádří.

**Comment by michal-josef-spacek** [comment]
Tak jsem tam minulý týden byl osobně, protože neodepsali. Dostal jsem povolení se podívat do Joomly a zkusit to opravit. Bohužel je to asi někde v nějakých komponentech, ke kterým nemají přístup. Dostal jsem slib, že napíšou svému konzultantovi.

**Comment by katkad** [comment]
Last run completed successfully 9 days ago.
